### PR TITLE
Add small subsection to README

### PR DESCRIPTION
**Pull request by steele232**
Added a section about seeing Jupyter notebook debugging logs.

Feel free to edit my exact wording
Merge can be --no-ff

### CODE REVIEW

**Comment by cosmos72** [comment]
Thanks :)

**Comment by steele232** [comment]
Thanks for taking the time to respond to my pull request. Did this get merged in? If not, that's fine. 
Thanks again for your time.

**Comment by cosmos72** [comment]
I thought I merged it, but checking again there's no trace of it.

My mistake, I will merge it ASAP

**Comment by cosmos72** [comment]
Added manually in commit 97ba7c0f9ecb5797ccc19111369cd614b7a8869b

Github says I cannot do a merge commit because "The repository that submitted this pull request has been deleted."

**Pull request closed without merging**
