### PR TITLE
all: use pure-Go implementation of zmq4

### LINKED ISSUE #199: Frequent kernel crashes if compiled with Go 1.14
The following error is logged on jupyter standard output:
```console
2020/02/26 23:59:16 Error polling heartbeat channel: interrupted system call
[I 23:59:18.358 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```
I suspect it's due to the Go runtime exposing more EINTR errors on interrupted system calls,
and libzmq (or some other code) not properly handling them - POSIX specs state that system calls can (and most of the times should) be called again when it happens.

Maybe switching to `go-zeromq/zmq4` (see pull request https://github.com/gopherdata/gophernotes/pull/195) could fix this?

### PR DESCRIPTION
**Pull request by sbinet**
Fixes #199

### CODE REVIEW

**Comment by sbinet** [comment]
this should enable an easier installation process on all platforms (as the `C/C++` `ZMQ0` library isn't needed anymore).

would be great to have (especially) Windows & macOS users give this a spin.

**Comment by sbinet** [comment]
FYI, I plan to:
- rebase this PR to use `go-zeromq/zmq4@v0.8.0` (when it's out: it's including a couple of bugfixes that could be relevant for this issue.)
- merge that PR a week after that rebase has happened (baring nobody reviewed/commented on it by then, of course)

**Comment by cosmos72** [comment]
Thanks @sbinet, this is a *very* welcome improvement!
I will review it ASAP

**Comment by sbinet** [comment]
PTAL.

**Comment by sbinet** [comment]
if nobody screams by Monday the 9th, I'll merge that in.

**Comment by mattn** [comment]
I tested this on Windows 64bit. Go 1.14 (tip). It works with importing standard packages. But importing external packages will be difficult on Windows since gomacros currently does not support dynamic import. (But this is not an issue of gophernotes and gomacros)

**Comment by sbinet** [comment]
> I think we can also remove the "Make sure you have the MinGW toolchain: ..." from the README as that toolchain was for building with the c dependencies.

done.

**Comment by sbinet** [comment]
merged and tagged (`v0.7.0`).
thanks everybody :)

**Comment by sbinet** [comment]
(@mattn could you devise an issue to reproduce this failure wrt `stdin`?)

**Pull request merged**
