### PR TITLE
First stab at implementing shell command.

### PR DESCRIPTION
**Pull request by Oshuma**
Issue #196

The only thing left is to steam stdout/stderr to Jupyter. I couldn't quite figure out how to do that, so if anyone could give me some pointers/examples, I can implement it.

### CODE REVIEW

**Comment by cosmos72** [comment]
Looks good, thanks :)
To stream stdout/stderr to Jupyter, you need three things:
1. get the stdout/stderr of the command as Go streams: you can use the methods `Cmd.StdoutPipe()` and `Cmd.StderrPipe()` of the struct `os/exec.Cmd` you are already using
2. create two `JupyterStreamWriter` structs - one with `stream = "StreamStdout"` and one with `stream = "StreamStderr"` -  you need a `msgReceipt` object for that, which must be passed to your `evalShellCommand` function)
3. a loop reading from `Cmd.StdoutPipe()` and writing into `JupyterStreamWriter`
4. another loop, reading from `Cmd.StderrPipe()` and writing into `JupyterStreamWriter`

at least one of the two loops probably needs to be executed from a dedicated goroutine - be careful to wait for the command to exit and for the goroutines to finish before returning from `evalShellCommand`

**Comment by Oshuma** [comment]
@cosmos72 Sounds good. I'll implement that as soon as I get a chance and update this PR.

**Comment by Oshuma** [comment]
@cosmos72 Can you verify/merge when you get a chance?

**Comment by cosmos72** [comment]
merged, with some little improvements.
Thanks!

**Pull request merged**
